Server/WebApplicationServer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplicationServer.Controllers {
    public class HomeController : Controller {
        public ActionResult Index() {
            return View();
        }

        public ActionResult About() {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact() {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Server/WebApplicationServer/Controllers/PresentationSupportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplicationServer.Controllers {

    public class PresentationSupportController : Controller {

        // GET: PresentationSupport
        public ActionResult Index() {
            return View();
        }

        // GET: PresentationSupport/RealtimeReaction
        public ActionResult RealtimeReaction() {
            return View();
        }

    }

}

Server/WebApplicationServer/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Server/WebApplicationServer/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Server/WebApplicationServer/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Server/WebApplicationServer/Views/PresentationSupport/Index.cshtml
@{
    ViewData["Title"] = "Index Page";
}

<div class="row">
    <div class="col-md-3">
        <h2>Prototype Application</h2>
        <p>
            Send the reaction in real time.
            <a href="./PresentationSupport/RealtimeReaction" class="btn btn-default">Realtime reaction</a>
        </p>
    </div>
</div>

Server/WebApplicationServer/Views/PresentationSupport/RealtimeReaction.cshtml
@{
    ViewData["Title"] = "Realtime reaction";
}

<div class="jumbotron">
    <h1>視聴者</h1>

    <button type="button" class="btn btn-primary btn-lg btn-block" id="sendGood">Good!</button>


</div>
<div class="row">
    <div class="col-md-4">
        <h2>使用方法</h2>
        <p>
            このページ上部の「 Good! 」を押します。

            正しく動作している場合、前の画面に ハート が表示されます。
        </p>
    </div>
    <div class="col-md-4">
        <h2>注意事項</h2>
        <p>
            使用しているサーバは、貧弱です。
            超!!!絶!!!連!!!打!!!とかされると、多分落ちます。
            まだテストは2人同時接続までしか行っていません。
            いじめ過ぎないで下さい。
        </p>
    </div>
    <div class="col-md-4">
        <h2>免責事項</h2>
        <p>
            コンテンツのご利用により、万一、ご利用者様に何らかの不都合や損害が発生したとしても、開発者は何らの責任を負うものではありません。
        </p>
    </div>
</div>
@section scripts {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>
        $(function () {

            // Reference the auto-generated proxy for the hub.
            var reactionHub = $.connection.realtimeReactionHub;
            //// Create a function that the hub can call back to display messages.
            //goods.client.getGood = function () {

            //    $('#discussion').append('<li><strong>' + (new Date()).toLocaleString() + '</li>');

            //};

            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendGood').click(function () {

                    // Call the Send method on the hub.
                    reactionHub.server.good();

                });
            });
        });
    </script>
}

Server/WebApplicationServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - マイ ASP.NET アプリケーション</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("アプリケーション名", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink( "ホーム", "Index", "Home" )</li>
                    <li>@Html.ActionLink( "詳細", "About", "Home" )</li>
                    <li>@Html.ActionLink( "問い合わせ", "Contact", "Home" )</li>
                    <li>@Html.ActionLink( "アプリ", "Index", "PresentationSupport" )</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - マイ ASP.NET アプリケーション</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>